name: chit_chat_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  circular_countdown:
    path: packages/circular_countdown-master/
  clipboard: ^0.1.3
  expandable_text: ^2.3.0
  firebase_core: ^2.28.0
  fluentui_emoji_icon: ^0.0.2
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_tts: ^4.0.1
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.2.1
  iconify_flutter_plus: ^1.0.3
  sliver_tools: ^0.2.12
  speech_to_text: ^6.6.0
  super_string: ^1.0.3
  text_to_speech:
    path: packages/text_to_speech/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env

  fonts:
    - family: LovelyMamma
      fonts:
        - asset: assets/fonts/lovelyMamma.ttf
