name: chit_chat_pro
description: "Chit Chat Pro is a cutting-edge application designed to emulate the functionalities of chat GPT, focusing on seamless communication and content creation. It integrates advanced features such as text-to-speech, speech-to-text, and image-to-text conversion, all wrapped in an efficient and user-friendly interface."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  circular_countdown:
    path: packages/circular_countdown-master/
  clipboard: ^0.1.3
  firebase_core: ^2.28.0
  fluentui_emoji_icon: ^0.0.2
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_tts: ^4.0.1
  gap: ^3.0.1
  get: ^4.6.6
  glowy_borders: ^1.0.2
  google_mlkit_text_recognition: ^0.11.0
  http: ^1.2.1
  iconify_flutter: 
    path: packages/iconify_flutter_plus/
  image_cropper: ^1.5.1
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  speech_to_text: ^6.6.0
  super_string: ^1.0.3
  text_to_speech:
    path: packages/text_to_speech/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/launcher_icon/launcher.jpeg"

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/launcher_icon/

  fonts:
    - family: LovelyMamma
      fonts:
        - asset: assets/fonts/lovelyMamma.ttf
